### PR TITLE
When moving between CC events, properly announce non control events

### LINKED ISSUE #436: Unable to use previous and next CC actions to move to events that are not CCs
The OSARA: Move to previous CC and OSARA: Move to next CC actions seem to treat all events that are not notes as CCs. So, if an item contains pitch bend, aftertouch, or program change messages, incorrect numbers and values are reported.

### PR DESCRIPTION
**Pull request by leonardder**
Fixes #436

Note that it looks like that the increase/decrease actions don't do anything for poly aftertouch and program. I think that's a REAPER bug that might need a report to Cockos.

### CODE REVIEW

File: src/midiEditorCommands.cpp [hunk 1]
```diff
@@ -805,8 +808,23 @@ void moveToCC(int direction, bool clearSelection=true, bool select=true) {
 	fakeFocus = FOCUS_CC;
 	ostringstream s;
 	s << formatCursorPosition(TF_MEASURE) << " ";
-	s << getMidiControlName(take, cc.control, cc.channel) << ", ";
-	s << cc.value;
+	if (cc.message1 == 0xA0) {
+		s << "Poly Aftertouch ";
+		// Note: separate the note and value with two spaces to avoid treatment as thausands separator.
```
Comment (jcsteh) [inline src/midiEditorCommands.cpp:813]: Typo
```suggestion
		// Note: separate the note and value with two spaces to avoid treatment as thousands separator.
```

**Comment by jcsteh** [comment]
Messed up a merge and had to force push, so this is now master b94a6c47.
